"""empty message

Revision ID: 9e46290da508
Revises: 600b4f0aaec1
Create Date: 2020-02-24 02:29:59.413380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e46290da508'
down_revision = '600b4f0aaec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movies_actor_id_fkey', 'movies', type_='foreignkey')
    op.drop_column('movies', 'actor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('movies_actor_id_fkey', 'movies', 'actors', ['actor_id'], ['id'])
    # ### end Alembic commands ###
