"""empty message

Revision ID: f89c1f1ea3fa
Revises: 
Create Date: 2020-04-16 13:07:21.135235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89c1f1ea3fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('actors', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.add_column('movies', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('movies', sa.Column('image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'image_link')
    op.drop_column('movies', 'created_date')
    op.drop_column('actors', 'image_link')
    op.drop_column('actors', 'created_date')
    # ### end Alembic commands ###
